spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: starjavawars-ddbb
      #username: user
      #password: pass

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.0

logging:
  level:
    root: DEBUG
    org.apache: ERROR
    org.springframework: ERROR